#!/usr/bin/env bash

SOURCE=${BASH_SOURCE[0]}

while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

export SCRIPT_ROOT=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
export LIBS_DIR="$SCRIPT_ROOT/libs"
export CMD_DIR="$SCRIPT_ROOT/commands"
export CUR_DIR="$(pwd)"
export PROJECT_DIR="$(dirname "$CUR_DIR")"
export SOURCE_DIR="$PROJECT_DIR/src"
export PATHS_DIR="$SOURCE_DIR/paths"
export SCHEMAS_DIR="$SOURCE_DIR/schemas"
export OUTPUT_FILE="$PROJECT_DIR/openapi.yaml"

echo "SCRIPT_ROOT: $SCRIPT_ROOT"

# Check if yq and jq are installed, if not, install them
if ! command -v yq &> /dev/null
then
  echo "yq could not be found, installing..."
  brew install yq
fi

if ! command -v jq &> /dev/null
then
  echo "jq could not be found, installing..."
  brew install jq
fi

source ${LIBS_DIR}/__echo.sh
source ${LIBS_DIR}/__define.sh


cmd=$1
shift

echo $cmd | echo

case $cmd in
  init)
    source ${CMD_DIR}/__init.sh
    ;;
  clean)
    source ${CMD_DIR}/__clean.sh
    ;;
  build)
    source ${CMD_DIR}/__compile.sh
    ;;
  help)
    source ${CMD_DIR}/__help.sh
    ;;
  *)
    source ${CMD_DIR}/__help.sh
    ;;
esac